# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true 

[directory]
truncation_length = 5
truncate_to_repo = false # Show full path in a repo

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
disabled = true

[cmd_duration]
disabled = true

[lua]
disabled = true

[pixi]
disabled = true
